project:
  type: website
  output-dir: docs

filters:
- nceas-learning-hub/theme
- quarto-ext/fontawesome
exercises: ### for custom theme callouts
  number: false ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html but does not work
editor: source
execute:
  freeze: auto

format:
  theme-html

website:
  title: "2026 Delta Synthesis Working Groups week 1 (April 2026)"
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/2026_delta_week1

  favicon: logo_lh_hex.png # learning hub logo on browser tab

  bread-crumbs: false
  navbar:
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: https://github.com/nceas-learning-hub/2026_delta_week1
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: nceas-learning-hub.github.io/2026_delta_week1
    contents:
      - index.qmd  # preface
      - groups.qmd # additional preface page
      # START SESSIONS
      - section: "Day 1"
        contents:
        - s01_r_rstudio_server_setup.qmd
        - s02_git_setup.qmd
        - s03_r_quarto_literate_analysis.qmd
        - s04_activity_reproducibility_lego.qmd
        - s05_blank_placeholder.qmd
        - s06_blank_placeholder.qmd
        - s07_blank_placeholder.qmd
        - s08_blank_placeholder.qmd
        - s09_blank_placeholder.qmd
      - section: "Day 3"
        contents:
        - s10_github_introduction.qmd
        - s11_lecture_data_mgmt_reproducibility.qmd
        - s17_blank_placeholder.qmd
      - section: "Day 4"
        contents:
        - s13_r_tidyverse_clean_wrangle.qmd
        - s14_r_practice_clean_wrangle_visualize.qmd
        - s15_r_functions.qmd
        - s16_r_packages.qmd
        - s17_blank_placeholder.qmd
      - section: "Day 5"
        contents:
        - s18_r_provenance_reproducibility.qmd
      # END SESSIONS

  page-footer:
    center: "Copyright \u00a9 2025, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


